 ## <span style='background :yellow' > Question 1: What percentage of trades are with 30+ DPD (more than 30 days past due) among all the trades available? </span>

In [1]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\rutik\appdata\local\programs\python\python310\lib\site-packages (4.8.0)

WARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Users\Rutik\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [2]:
# Importing libraries 
import os
import json
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
os.listdir()[1:11]

['customer1113697_loan1115483_crif_report.html.xml',
 'customer1129550_loan1131339_crif_report.html.xml',
 'customer1195586_loan1197471_crif_report.html.xml',
 'customer14235_loan14235_crif_report.html.xml',
 'customer16475_loan16475_crif_report.html.xml',
 'customer40409_loan40409_crif_report.html.xml',
 'customer773504_loan774538_crif_report.html.xml',
 'customer787561_loan788638_crif_report.html.xml',
 'customer794397_loan795497_crif_report.html.xml',
 'customer898231_loan899591_crif_report.html.xml']

In [4]:


history=[]

for i in os.listdir()[1:11]:  
    with open(i, 'r') as f:   # Opening all 10 customer files
        xml_data=f.read()
        bs_data = BeautifulSoup(xml_data, 'xml') 
        payment_history=bs_data.find_all("COMBINED-PAYMENT-HISTORY")  # Getting Payment data From all XML files
        for i in payment_history:
                history.append(i.text)
                

History_split=[]
import re

# Removing Unwanted Object from data
for i in history:

    a=re.split(r'[,|,\s,'',]',i)
#     print(a,'\n')
    History_split.append(a)

        
for i in History_split:       # Removing unwanted using pop 
    removespace=i.pop(-1)
    

    
# Coverting Data Into dictionary (key:Value Format)
main_history=[]     
def Convert(lst):
    res_dct = map(lambda i: (lst[i], lst[i+1]), range(len(lst)-1)[::2])
    return dict(res_dct)
 
for i in History_split:
    sample=(Convert(i))
    main_history.append(sample)
    
    
data=pd.DataFrame(main_history)             # Creating DataFrame

# Replacing unwanted part of data into emptystring
for i in data.columns:           
    data[i]=data[i].str.replace('/','').astype(str)

# Replacing unwanted part of data into emptystring    
for i in data.columns:
    data[i]=(data[i].str.replace("[XXXSTDDDDSUBDBTLO]",""))
 

#removing nan string data into empty string
for i in data.columns:
    data[i]=(data[i].str.replace("[nan]",""))
    
    
list1=data.values.tolist()  # Converting list data into DataFrame with Pandas


NewList=[]                # Seperating Numeric Data For Calculation
for a in list1:
     for b in a:
          if b.isnumeric():
                NewList.append(b)
            
NewList=list(map(int,NewList))     # Converting Datatype String into integer

C:\Users\Rutik\AppData\Local\Temp/ipykernel_23544/1333465780.py:47: FutureWarning: The default value of regex will change from True to False in a future version.
  data[i]=(data[i].str.replace("[XXXSTDDDDSUBDBTLO]",""))
C:\Users\Rutik\AppData\Local\Temp/ipykernel_23544/1333465780.py:52: FutureWarning: The default value of regex will change from True to False in a future version.
  data[i]=(data[i].str.replace("[nan]",""))

In [5]:
df=pd.DataFrame(NewList) # CReating DataFrame
df.rename(columns={0: "Days_Past_Due"}, inplace=True) # Changing Column name in the DataFrame

In [6]:
df       # Data of past dues

      Days_Past_Due
0                 0
1                 0
2                 0
3               175
4               146
...             ...
2577              0
2578              0
2579              0
2580              0
2581              0

[2582 rows x 1 columns]

In [7]:
# Calculating data which have  30+ DPD
trades_with_30Plus =0    
for i in NewList:
    if i >30:
        trades_with_30Plus+=1
trades_with_30Plus

391

In [8]:
Answer=( trades_with_30Plus/len(NewList)*100)
print('trades are with 30+ DPD (more than 30 days past due) among all  the trades available',Answer,"%")

trades are with 30+ DPD (more than 30 days past due) among all  the trades available 15.143299767621999 %

### Answer: Question 1
##  Percentage Trades are with 30+ DPD (more than 30 days past due) among all  the trades available = 15.143299767621999 %

*** 
*** 
***

## <span style='background :yellow' > Question 2: What is the sum of total disbursed amount for all loans for each customer? </span>

In [9]:
# Importing imp libraries 
import os
import json
from bs4 import BeautifulSoup
import pandas as pd

In [10]:
os.listdir()[1:11]

['customer1113697_loan1115483_crif_report.html.xml',
 'customer1129550_loan1131339_crif_report.html.xml',
 'customer1195586_loan1197471_crif_report.html.xml',
 'customer14235_loan14235_crif_report.html.xml',
 'customer16475_loan16475_crif_report.html.xml',
 'customer40409_loan40409_crif_report.html.xml',
 'customer773504_loan774538_crif_report.html.xml',
 'customer787561_loan788638_crif_report.html.xml',
 'customer794397_loan795497_crif_report.html.xml',
 'customer898231_loan899591_crif_report.html.xml']

In [11]:
Loan_amount=[]
history=[]

# Reading all XML files of Customer
for i in os.listdir()[1:-3]:       
    with open(i, 'rb') as f:
        xml_data=f.read()
        bs_data = BeautifulSoup(xml_data, 'xml') 
        
        DISBURSED_AMT=bs_data.find_all("DISBURSED-AMT")     # Getting Data
        
        for i in DISBURSED_AMT:
                Loan_amount.append(i.text)                  # Text data of DISBURSED AMT

In [12]:
Final_Amount=[]
for i in Loan_amount:                                      # Splitting Data and appending into New List   
        b=''.join(str(i).split(','))
        Final_Amount.append(b)



Final_Amount                                               # Calculating Sum of Data

['35000',
 '31500',
 '31500',
 '12000',
 '6400',
 '15500',
 '70000',
 '45000',
 '20000',
 '47000',
 '35000',
 '20000',
 '5000',
 '20000',
 '130000',
 '21600',
 '21600',
 '50000',
 '20000',
 '165000',
 '11500',
 '11500',
 '40000',
 '46980',
 '11340',
 '38000',
 '52000',
 '62000',
 '35000',
 '12500',
 '10100',
 '22000',
 '22000',
 '9500',
 '32500',
 '8100',
 '1',
 '9200',
 '65100',
 '11100',
 '500000',
 '93500',
 '129000',
 '87700',
 '291500',
 '45614',
 '45614',
 '45614',
 '45614',
 '299000',
 '26740',
 '87700',
 '317000',
 '100000',
 '129000',
 '129000',
 '638536',
 '87700',
 '16032',
 '85841',
 '291500',
 '1710000',
 '1800000',
 '1710000',
 '824000',
 '100000',
 '127341',
 '89258',
 '900000',
 '130405',
 '22999',
 '375000',
 '35000',
 '121094',
 '200000',
 '300000',
 '42000',
 '60000',
 '70000',
 '301000',
 '985000',
 '57580',
 '1228599',
 '650000',
 '34819',
 '47148',
 '532',
 '55666',
 '100000',
 '375000',
 '130000',
 '130000',
 '97983',
 '114304',
 '35269',
 '62055',
 '34028',
 '107635',
 '200000',
 '155677',
 '15390',
 '55666',
 '160000',
 '0',
 '114304',
 '114304',
 '114304',
 '329914',
 '282621',
 '221850',
 '54997',
 '104929',
 '10000',
 '5000',
 '8000',
 '132000',
 '250000',
 '12700',
 '8000',
 '7992',
 '10000',
 '10242',
 '8000',
 '39000',
 '38000',
 '8000',
 '21631',
 '38700',
 '656354',
 '60000',
 '636761',
 '10000',
 '16607',
 '10000',
 '37972',
 '135000',
 '17409',
 '25000',
 '27000',
 '10000',
 '8000',
 '5000',
 '39516',
 '38700',
 '38700',
 '10000',
 '41363',
 '56044',
 '33000',
 '44990',
 '17926',
 '100000',
 '52602',
 '6000',
 '38221',
 '10000',
 '58276',
 '37000',
 '40000',
 '23990',
 '23200',
 '4000',
 '1000',
 '71000',
 '48619',
 '50000',
 '149621',
 '46273',
 '11000',
 '10000',
 '4000',
 '46273',
 '60261',
 '11790',
 '16266',
 '60000',
 '152244',
 '7000',
 '34230',
 '51000',
 '16999',
 '60000',
 '218876',
 '108798',
 '99698',
 '213844',
 '11000',
 '13990',
 '213844',
 '185146',
 '68347',
 '5000',
 '14478',
 '17604',
 '15500',
 '132000',
 '132000',
 '132000',
 '19999',
 '191081',
 '103171',
 '303814',
 '485000',
 '10000',
 '310161',
 '146436',
 '71352',
 '47687',
 '7809',
 '66000',
 '500000',
 '5000',
 '10000',
 '84257',
 '132000',
 '3500',
 '30551',
 '46000',
 '91000',
 '1799',
 '3500',
 '114000',
 '1979',
 '39000',
 '39000',
 '3500',
 '3500',
 '30200',
 '37999',
 '5000',
 '9484',
 '9000',
 '16500',
 '29575',
 '5000',
 '3500',
 '8800',
 '80000',
 '80000',
 '24240',
 '5000',
 '12661',
 '11999',
 '30552',
 '4000',
 '25000',
 '5000',
 '36000',
 '31395',
 '4700',
 '27900',
 '30000',
 '9000',
 '44034',
 '29000',
 '11400',
 '42500',
 '19500',
 '25900',
 '6000',
 '18804',
 '8530',
 '39990',
 '13500',
 '19120',
 '54600',
 '10268',
 '45000',
 '47996',
 '6005',
 '71410',
 '5249',
 '25600',
 '17000',
 '8000',
 '46000',
 '18800',
 '50300',
 '21990',
 '41700',
 '7000',
 '16600']

In [13]:
df2=pd.DataFrame(Final_Amount)                             # Creating DataFrame 
df2.rename(columns={0: "DISBURSED-AMT"}, inplace=True)     # Renaming The column for Better Understanding

In [14]:
df2

    DISBURSED-AMT
0           35000
1           31500
2           31500
3           12000
4            6400
..            ...
277         50300
278         21990
279         41700
280          7000
281         16600

[282 rows x 1 columns]

In [15]:
df2 = df2.astype({'DISBURSED-AMT':'int'})                  # Changing Datatype of data
df2.sum()

DISBURSED-AMT    29573391
dtype: int64

In [16]:
df2

     DISBURSED-AMT
0            35000
1            31500
2            31500
3            12000
4             6400
..             ...
277          50300
278          21990
279          41700
280           7000
281          16600

[282 rows x 1 columns]

In [17]:
df2.loc['Grand_total']= df2.sum()         # Adding Column Grand Total Into DataFrame
df2

             DISBURSED-AMT
0                    35000
1                    31500
2                    31500
3                    12000
4                     6400
...                    ...
278                  21990
279                  41700
280                   7000
281                  16600
Grand_total       29573391

[283 rows x 1 columns]

### Answer: Question 2
## Sum of total disbursed amount for all loans for each customer :42579056

*** 
---
___

## <span style='background :yellow' > Question 3:What is the maximum number of months of 30+ due per trade was there?
 </span>

In [18]:
history=[]

for i in os.listdir()[1:11]:  
    with open(i, 'rb') as f:   # Opening all 10 customer files
        xml_data=f.read()
        bs_data = BeautifulSoup(xml_data, 'xml') 
        payment_history=bs_data.find_all("COMBINED-PAYMENT-HISTORY")  # Getting Payment data From all XML files
        for i in payment_history:
                history.append(i.text)
                

History_split=[]
import re

# Removing Unwanted Object from data
for i in history:

    a=re.split(r'[,|,\s,'',]',i)
#     print(a,'\n')
    History_split.append(a)

        
for i in History_split:       # Removing unwanted using pop 
    removespace=i.pop(-1)
    

    
# Coverting Data Into dictionary (key:Value Format)
main_history=[]     
def Convert(lst):
    res_dct = map(lambda i: (lst[i], lst[i+1]), range(len(lst)-1)[::2])
    return dict(res_dct)
 
for i in History_split:
    sample=(Convert(i))
    main_history.append(sample)
    
    
data1=pd.DataFrame(main_history)             # Creating DataFrame

# Replacing unwanted part of data into emptystring
for i in data.columns:           
    data1[i]=data1[i].str.replace('/','').astype(str)

# Replacing unwanted part of data into emptystring    
for i in data.columns:
    data1[i]=(data1[i].str.replace("[XXXSTDDDDSUBDBTLO]",""))
 

#removing nan string data into empty string
for i in data1.columns:
    data1[i]=(data1[i].str.replace("[nan]",""))
    
    
list1=data1.values.tolist()  # Converting list data into DataFrame with Pandas

C:\Users\Rutik\AppData\Local\Temp/ipykernel_23544/171038715.py:47: FutureWarning: The default value of regex will change from True to False in a future version.
  data1[i]=(data1[i].str.replace("[XXXSTDDDDSUBDBTLO]",""))
C:\Users\Rutik\AppData\Local\Temp/ipykernel_23544/171038715.py:52: FutureWarning: The default value of regex will change from True to False in a future version.
  data1[i]=(data1[i].str.replace("[nan]",""))

In [19]:
# Seprating Numeric values for calculation and adding them into new list

NewList=[]
for a in list1:
     x=[]
     for b in a:
          if b.isnumeric():
                x.append(b)
     NewList.append(x)

In [20]:
# Removing Empty list Data from DATA

res = [ele for ele in NewList if ele != []]

# Changing Data Type of the Data
new_l=[]
for i in res:
    h=list(map(int, i))
    new_l.append(h)
    
new_l

[[0, 0],
 [0, 175, 146, 0, 0, 108, 46, 1, 0, 0, 0],
 [114, 86, 0, 55, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0],
 [0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 172, 143, 0, 0, 108, 46, 1, 0, 0, 0],
 [0, 0],
 [0],
 [120, 0, 210, 180, 150],
 [73, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0],
 [0],
 [0],
 [113, 82, 0, 141],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 53],
 [0, 93, 62, 0, 0, 0, 0, 32],
 [334, 304, 273, 242, 212, 181, 151, 120, 92, 1],
 [0, 0, 0],
 [0, 0],
 [0, 0, 28, 0, 0, 0],
 [0, 0, 0],
 [0, 0, 125, 94, 31, 2, 0, 0, 64],
 [0, 0, 0, 0, 90, 59, 28, 0, 0, 0],
 [0, 0, 0, 0, 90, 59, 28, 0, 0, 0],
 [80, 52, 0, 21, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  27,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 66, 35, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  92,
  62,
  31,
  0,
  0,
  0,
  0,
  0,
  0,
  1],
 [0, 5, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  118,
  88,
  57,
  0,
  0,
  0,
  0,
  0,
  0,
  27],
 [0, 25, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 25, 0, 0, 0, 0, 0, 0],
 [0, 14, 0, 0, 0, 0, 0],
 [7, 0, 0, 0, 0, 0, 0, 0, 68, 37],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0],
 [60, 30, 0, 0, 0, 0, 0, 0, 0],
 [0, 0],
 [90, 90, 90, 60, 30, 15, 15, 0, 15, 0, 15, 0, 120, 120, 90],
 [0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  56,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [180, 150],
 [0, 738, 0],
 [0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
 [0, 0],
 [0,
  0,
  60,
  60,
  28,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [120, 90, 60],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [54,
  56,
  0,
  57,
  86,
  56,
  25,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0],
 [0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0],
 [0, 0, 0],
 [0, 77, 46, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 52, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0],
 [0],
 [0, 0, 0],
 [0],
 [0, 78, 47, 16, 0, 0, 0, 0, 0, 0],
 [0, 49, 19, 0, 0, 0, 0, 0, 0],
 [0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  26,
  25,
  0,
  0,
  26,
  55,
  0,
  25],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 9, 0, 9, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0],
 [0],
 [0, 0, 5, 0, 0, 0, 0, 0],
 [329, 298, 270, 239, 178],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  58,
  30,
  24,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 26, 23, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0],
 [0],
 [0, 0, 28, 29, 26, 0, 0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 93, 63, 33, 3, 0, 0, 0, 0, 0],
 [93, 63, 33, 3, 3, 0, 0],
 [0, 0],
 [160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160],
 [0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360],
 [180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 354, 322],
 [0],
 [0, 0, 0, 0, 0, 0],
 [900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900],
 [900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0],
 [80, 80, 49, 18],
 [0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 59, 0, 0, 89, 0],
 [0, 0, 0, 0, 0, 0, 0, 59, 0, 0, 89, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 1, 0],
 [0, 0],
 [0, 0],
 [0, 0, 0],
 [0, 0, 0, 0],
 [0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 77, 0, 0, 0],
 [0],
 [0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0],
 [0],
 [0, 0, 0, 0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [49, 0, 80, 0, 0, 0, 171, 141, 110],
 [0, 0, 0, 0, 52, 0],
 [0],
 [0, 0],
 [0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0],
 [0,
  0,
  0,
  0,
  0,
  10,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 60, 0, 0, 0, 0, 59, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [179, 87, 56, 54, 23, 26, 25, 26, 0, 26, 0, 0, 148, 117],
 [0, 0, 0, 0, 0, 0, 0],
 [0],
 [60, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0],
 [0],
 [0],
 [0],
 [0],
 [0, 0],
 [0, 0],
 [0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0],
 [115,
  90,
  60,
  28,
  29,
  0,
  28,
  29,
  20,
  51,
  51,
  20,
  0,
  0,
  0,
  0,
  20,
  148,
  59,
  119,
  89,
  58,
  0,
  88,
  60,
  178,
  89,
  147,
  120,
  89,
  120],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 67, 36, 6, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 43, 0, 0, 0, 0, 13],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 67, 36, 5, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 67, 37, 6, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 0, 0, 0, 0]]

In [21]:
# Finding Values Which Are greater than 30
trade=[]
for i in new_l :
    k=[]
    for j in i:
        if j > 30:
            k.append(j)
    trade.append(k)
trade

[[],
 [175, 146, 108, 46],
 [114, 86, 55],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [172, 143, 108, 46],
 [],
 [],
 [120, 210, 180, 150],
 [73],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [113, 82, 141],
 [],
 [],
 [],
 [],
 [53],
 [93, 62, 32],
 [334, 304, 273, 242, 212, 181, 151, 120, 92],
 [],
 [],
 [],
 [],
 [125, 94, 31, 64],
 [90, 59],
 [90, 59],
 [80, 52],
 [],
 [66, 35],
 [92, 62, 31],
 [],
 [],
 [118, 88, 57],
 [],
 [],
 [],
 [],
 [68, 37],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [60],
 [],
 [90, 90, 90, 60, 120, 120, 90],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [56],
 [180, 150],
 [738],
 [],
 [],
 [],
 [60, 60],
 [],
 [],
 [120, 90, 60],
 [],
 [],
 [],
 [],
 [],
 [54, 56, 57, 86, 56],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [77, 46],
 [],
 [52],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [78, 47],
 [49],
 [],
 [55],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [39],
 [],
 [],
 [],
 [],
 [],
 [329, 298, 270, 239, 178],
 [58],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [93, 63, 33],
 [93, 63, 33],
 [],
 [160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160,
  160],
 [],
 [],
 [],
 [],
 [],
 [360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360,
  360],
 [180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180,
  180],
 [],
 [354, 322],
 [],
 [],
 [900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900],
 [],
 [],
 [],
 [],
 [],
 [],
 [900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900],
 [900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900,
  900],
 [],
 [],
 [],
 [190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190,
  190],
 [],
 [],
 [],
 [],
 [],
 [],
 [80, 80, 49],
 [],
 [],
 [59, 89],
 [59, 89],
 [],
 [],
 [],
 [],
 [31],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [77],
 [],
 [],
 [],
 [31],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [49, 80, 171, 141, 110],
 [52],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [60, 59],
 [],
 [179, 87, 56, 54, 148, 117],
 [],
 [],
 [60],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [115,
  90,
  60,
  51,
  51,
  148,
  59,
  119,
  89,
  58,
  88,
  60,
  178,
  89,
  147,
  120,
  89,
  120],
 [],
 [],
 [],
 [],
 [67, 36],
 [],
 [],
 [],
 [],
 [],
 [],
 [43],
 [],
 [],
 [67, 36],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [67, 37],
 [],
 [],
 []]

In [22]:
# Showing 30+ DPD occurance 

maximum=[]
Statement=[]
b=1
for i in trade:
        maximum.append(len(i))
        x=(' The number of occurrences which are 30+ DPD For Trade' ,b, 'is',len(i))
        Statement.append(x)
        
        b+=1

In [23]:
Statement

[(' The number of occurrences which are 30+ DPD For Trade', 1, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 2, 'is', 4),
 (' The number of occurrences which are 30+ DPD For Trade', 3, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 4, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 5, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 6, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 7, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 8, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 9, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 10, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 11, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 12, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 13, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 14, 'is', 4),
 (' The number of occurrences which are 30+ DPD For Trade', 15, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 16, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 17, 'is', 4),
 (' The number of occurrences which are 30+ DPD For Trade', 18, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 19, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 20, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 21, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 22, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 23, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 24, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 25, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 26, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 27, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 28, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 29, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 30, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 31, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 32, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 33, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 34, 'is', 9),
 (' The number of occurrences which are 30+ DPD For Trade', 35, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 36, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 37, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 38, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 39, 'is', 4),
 (' The number of occurrences which are 30+ DPD For Trade', 40, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 41, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 42, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 43, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 44, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 45, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 46, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 47, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 48, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 49, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 50, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 51, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 52, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 53, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 54, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 55, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 56, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 57, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 58, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 59, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 60, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 61, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 62, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 63, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 64, 'is', 7),
 (' The number of occurrences which are 30+ DPD For Trade', 65, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 66, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 67, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 68, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 69, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 70, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 71, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 72, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 73, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 74, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 75, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 76, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 77, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 78, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 79, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 80, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 81, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 82, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 83, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 84, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 85, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 86, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 87, 'is', 5),
 (' The number of occurrences which are 30+ DPD For Trade', 88, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 89, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 90, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 91, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 92, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 93, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 94, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 95, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 96, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 97, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 98, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 99, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 100, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 101, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 102, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 103, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 104, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 105, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 106, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 107, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 108, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 109, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 110, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 111, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 112, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 113, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 114, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 115, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 116, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 117, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 118, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 119, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 120, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 121, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 122, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 123, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 124, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 125, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 126, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 127, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 128, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 129, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 130, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 131, 'is', 5),
 (' The number of occurrences which are 30+ DPD For Trade', 132, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 133, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 134, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 135, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 136, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 137, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 138, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 139, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 140, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 141, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 142, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 143, 'is', 36),
 (' The number of occurrences which are 30+ DPD For Trade', 144, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 145, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 146, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 147, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 148, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 149, 'is', 35),
 (' The number of occurrences which are 30+ DPD For Trade', 150, 'is', 36),
 (' The number of occurrences which are 30+ DPD For Trade', 151, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 152, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 153, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 154, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 155, 'is', 35),
 (' The number of occurrences which are 30+ DPD For Trade', 156, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 157, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 158, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 159, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 160, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 161, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 162, 'is', 36),
 (' The number of occurrences which are 30+ DPD For Trade', 163, 'is', 36),
 (' The number of occurrences which are 30+ DPD For Trade', 164, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 165, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 166, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 167, 'is', 31),
 (' The number of occurrences which are 30+ DPD For Trade', 168, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 169, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 170, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 171, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 172, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 173, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 174, 'is', 3),
 (' The number of occurrences which are 30+ DPD For Trade', 175, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 176, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 177, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 178, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 179, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 180, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 181, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 182, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 183, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 184, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 185, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 186, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 187, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 188, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 189, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 190, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 191, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 192, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 193, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 194, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 195, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 196, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 197, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 198, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 199, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 200, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 201, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 202, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 203, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 204, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 205, 'is', 5),
 (' The number of occurrences which are 30+ DPD For Trade', 206, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 207, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 208, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 209, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 210, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 211, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 212, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 213, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 214, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 215, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 216, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 217, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 218, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 219, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 220, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 221, 'is', 6),
 (' The number of occurrences which are 30+ DPD For Trade', 222, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 223, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 224, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 225, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 226, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 227, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 228, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 229, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 230, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 231, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 232, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 233, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 234, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 235, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 236, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 237, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 238, 'is', 18),
 (' The number of occurrences which are 30+ DPD For Trade', 239, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 240, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 241, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 242, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 243, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 244, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 245, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 246, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 247, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 248, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 249, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 250, 'is', 1),
 (' The number of occurrences which are 30+ DPD For Trade', 251, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 252, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 253, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 254, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 255, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 256, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 257, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 258, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 259, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 260, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 261, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 262, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 263, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 264, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 265, 'is', 2),
 (' The number of occurrences which are 30+ DPD For Trade', 266, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 267, 'is', 0),
 (' The number of occurrences which are 30+ DPD For Trade', 268, 'is', 0)]

In [24]:
df3=pd.DataFrame(Statement)

In [25]:
# Calculating Max number of moths with 30+ Occurance

In [26]:
print('The maximum number of months of 30+ due per trade:', max(maximum))

The maximum number of months of 30+ due per trade: 36

### Answer: Question 3
# The maximum number of months of 30+ due per trade is 36

*** 
---
___

## importing data of All Questions into Excel

In [27]:

with pd.ExcelWriter("zproject.xlsx", engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Question_1",header=True, index=False)
    df2.to_excel(writer, sheet_name="Question_2",  header=True, index=False) 
    df3.to_excel(writer, sheet_name="Question_3", header=True, index=False)

ModuleNotFoundError: No module named 'openpyxl'